Lower warnlevel to 0
Workaround for:

[9/816] Compiling C object externals/cgns/hdf5/libsu2hdf5.a.p/H5system.c.o
FAILED: externals/cgns/hdf5/libsu2hdf5.a.p/H5system.c.o
ccache cc -Iexternals/cgns/hdf5/libsu2hdf5.a.p -Iexternals/cgns/hdf5 -I../externals/cgns/hdf5 -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c99 -O3 -fPIC -pthread -Wno-unused-result -Wno-unused-parameter -Wno-unused-variable -Wno-unused-but-set-variable -Wno-sign-compare -Wno-stringop-overflow -Wno-discarded-qualifiers -Wno-error=maybe-uninitialized -Wno-error=unused-function -Wno-error=unused-label -Wno-pedantic -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200809L -D_GNU_SOURCE -MD -MQ externals/cgns/hdf5/libsu2hdf5.a.p/H5system.c.o -MF externals/cgns/hdf5/libsu2hdf5.a.p/H5system.c.o.d -o externals/cgns/hdf5/libsu2hdf5.a.p/H5system.c.o -c ../externals/cgns/hdf5/H5system.c
In file included from /usr/include/string.h:495,
                 from ../externals/cgns/hdf5/H5private.h:58,
                 from ../externals/cgns/hdf5/H5system.c:33:
In function ‘strncat’,
    inlined from ‘H5_build_extpath’ at ../externals/cgns/hdf5/H5system.c:858:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: error: ‘__builtin_strncat’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
  136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../externals/cgns/hdf5/H5system.c:33:
../externals/cgns/hdf5/H5system.c: In function ‘H5_build_extpath’:
../externals/cgns/hdf5/H5private.h:1448:28: note: length computed here
 1448 | #define HDstrncat(X, Y, Z) strncat(X, Y, Z)
      |                            ^~~~~~~~~~~~~~~~
../externals/cgns/hdf5/H5system.c:858:13: note: in expansion of macro ‘HDstrncat’
  858 |             HDstrncat(full_path, new_name, HDstrlen(new_name));
      |             ^~~~~~~~~
cc1: all warnings being treated as errors
[10/816] Compiling C object externals/cgns/hdf5/libsu2hdf5.a.p/H5timer.c.o
[11/816] Compiling C object externals/cgns/hdf5/H5detect.p/H5detect.c.o

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>