Add exclusion for -Werror=class-memaccess
Needed because of:

FAILED: Common/src/libSU2CommonDD.a.p/linear_algebra_CSysMatrix.cpp.o
ccache c++ -ICommon/src/libSU2CommonDD.a.p -ICommon/src -I../Common/src -I../externals/CLI11 -I../externals/cgns/adf -I../externals/cgns/adfh -Iexternals/cgns -I../externals/cgns -Iexternals/cgns/hdf5 -I../externals/cgns/hdf5 -I../externals/metis/include -I../externals/metis/GKlib -I../externals/metis/libmetis -I../externals/parmetis/include -I../externals/parmetis/libparmetis -Iexternals/tecio -I../externals/tecio -Iexternals/tecio/teciompisrc -I../externals/tecio/teciompisrc -I../externals/mel -I../externals/codi/include -I../externals/medi/include -I../externals/medi/src -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -Werror -std=c++11 -O3 -fPIC -pthread -Wno-empty-body -Wno-unused-parameter -Wno-deprecated-declarations -Wno-error=cast-function-type -Wno-cast-function-type -Wno-error=stringop-truncation -Wno-stringop-truncation -Wno-error=missing-field-initializers -Wno-missing-field-initializers -Wno-non-virtual-dtor -DHAVE_CGNS -DNDEBUG -DHAVE_MPI -DHAVE_METIS -DHAVE_PARMETIS -DHAVE_TECIO -DTECIOMPI -DCODI_FORWARD_TYPE -MD -MQ Common/src/libSU2CommonDD.a.p/linear_algebra_CSysMatrix.cpp.o -MF Common/src/libSU2CommonDD.a.p/linear_algebra_CSysMatrix.cpp.o.d -o Common/src/libSU2CommonDD.a.p/linear_algebra_CSysMatrix.cpp.o -c ../Common/src/linear_algebra/CSysMatrix.cpp
../Common/src/linear_algebra/CSysMatrix.cpp: In instantiation of ‘void CSysMatrix<ScalarType>::SetValZero() [with ScalarType = codi::ActiveReal<codi::ForwardEvaluation<codi::ForwardTapeTypes<double, double> > >]’:
../Common/src/linear_algebra/CSysMatrix.cpp:1438:1:   required from here
../Common/src/linear_algebra/CSysMatrix.cpp:492:9: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘class codi::ActiveReal<codi::ForwardEvaluation<codi::ForwardTapeTypes<double, double> > >’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  492 |   memset(&matrix[begin], 0, mySize);
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../externals/codi/include/codi.hpp:35,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/../../include/parallelization/../basic_types/../code_config.hpp:106,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/../../include/parallelization/../basic_types/datatype_structure.hpp:34,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/../../include/parallelization/mpi_structure.hpp:37,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/../../include/CConfig.hpp:31,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/CSysMatrix.hpp:31,
                 from ../Common/src/linear_algebra/../../include/linear_algebra/CSysMatrix.inl:33,
                 from ../Common/src/linear_algebra/CSysMatrix.cpp:28:
../externals/codi/include/codi/activeReal.hpp:80:9: note: ‘class codi::ActiveReal<codi::ForwardEvaluation<codi::ForwardTapeTypes<double, double> > >’ declared here
   80 |   class ActiveReal : public Expression<typename Tape::Real, ActiveReal<Tape> > {
      |         ^~~~~~~~~~
cc1plus: all warnings being treated as errors
[538/796] Compiling C++ object Common/src/libSU2CommonDD.a.p/toolboxes_printing_toolbox.cpp.o
[539/796] Compiling C++ object Common/src/libSU2CommonDD.a.p/CConfig.cpp.o
ninja: build stopped: subcommand failed.

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>